// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjs-8Z1pNdiE_jm2b8gbzhx9TizkU4sms',
    appId: '1:69584731624:web:c5bfec73880602b4dfb85d',
    messagingSenderId: '69584731624',
    projectId: 'leaf-lab-7a828',
    authDomain: 'leaf-lab-7a828.firebaseapp.com',
    storageBucket: 'leaf-lab-7a828.appspot.com',
    measurementId: 'G-NRZLSTCLS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeVUZTg9EsR_oJcoNiCtq1Ze9KUs9Twc8',
    appId: '1:69584731624:android:be1aa5ef8c16cea8dfb85d',
    messagingSenderId: '69584731624',
    projectId: 'leaf-lab-7a828',
    storageBucket: 'leaf-lab-7a828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhbWAx5yNgKUwl2uiFNw_GatdQ3oAnhs',
    appId: '1:69584731624:ios:e65205e3170c919ddfb85d',
    messagingSenderId: '69584731624',
    projectId: 'leaf-lab-7a828',
    storageBucket: 'leaf-lab-7a828.appspot.com',
    iosBundleId: 'com.Abhinav.leafLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVhbWAx5yNgKUwl2uiFNw_GatdQ3oAnhs',
    appId: '1:69584731624:ios:e65205e3170c919ddfb85d',
    messagingSenderId: '69584731624',
    projectId: 'leaf-lab-7a828',
    storageBucket: 'leaf-lab-7a828.appspot.com',
    iosBundleId: 'com.Abhinav.leafLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjs-8Z1pNdiE_jm2b8gbzhx9TizkU4sms',
    appId: '1:69584731624:web:72c47935edc8186edfb85d',
    messagingSenderId: '69584731624',
    projectId: 'leaf-lab-7a828',
    authDomain: 'leaf-lab-7a828.firebaseapp.com',
    storageBucket: 'leaf-lab-7a828.appspot.com',
    measurementId: 'G-ZR4N0WN798',
  );
}
